### ISSUE TITLE
Add support for MacOS and Radeon 

### ISSUE THREAD

**Issue by mrhammadasif** [grantwilk/DNOISE#43]
Would love to see the plugin working in MacOS for Radeon cards...

**Comment by grantwilk** [comment]
Thanks for the recommendation! Unfortunately I am unable to add MacOS support because I do not have access to a Mac system to develop on. However, if someone from the community can recompile the necessary code to work on MacOS, I will absolutely be integrating it.

Additionally, AMD cards can not be supported because D-NOISE relies on a proprietary AI denoiser from NVIDIA that can only run on NVIDIA cards.

Marking this issue as closed, but thank you for your support and interest!
