### ISSUE TITLE
D-Noise not denoising

### ISSUE THREAD

**Issue by Odaiho** [grantwilk/DNOISE#53]
I downloaded D-noise today both for blender 2.80 and 2.79, in both cases when it has to denoise a scene that i made it creates a denoised output but there is the same amount of noise, I tried: uninstalling, installing, changing the optix files a couple of times installing again blender, nothing has changed it doesn't denoise the images, what could it be the problem?

For the renders I'm running a Nvidia Geforce 1080ti and for CPU intel core i7 8700k.

i tried with 3 different files and nothing changes

**Comment by dev369** [comment]
since he still not updated it i believe it should still be broken. its not as good as he claims it to be anyways(yes his examples were cherry-picked). in depends A LOT on the scene, i found more often then not regular blender denoiser did a better job. hopefully d-noise gets fixed soon and gets a more intelligent implementation of nvidia's ai denoise one that will more often then not be better then regular denoising methods.
